# Generated by Django 5.2.3 on 2025-06-20 20:52

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=250, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of created item', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.CharField(help_text='please enter a serial number of this batch', max_length=250, verbose_name='Batch number'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='stock',
            field=models.ForeignKey(help_text='please select a stock from the list', on_delete=django.db.models.deletion.PROTECT, to='stocks.stock', verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date of created item', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of created item', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(help_text='Please enter name of stock', max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='please select a parent stock from the list', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stocks.stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date of updated item', verbose_name='Updated'),
        ),
    ]
