# Generated by Django 5.2.3 on 2025-06-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_balance_slug_alter_batch_created_alter_batch_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=250, unique=True, verbose_name='slug'),
        ),
    ]
